// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Banco
    {
        public Banco()
        {
            Cuenta = new HashSet<Cuentum>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
         public string Estado { get; set; } ="A"; 

        public virtual ICollection<Cuentum> Cuenta { get; set; }
    }
}