// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Ciudad
    {
        public Ciudad()
        {
            Clientes = new HashSet<Cliente>();
            Empleados = new HashSet<Empleado>();
            Personas = new HashSet<Persona>();
            Proveedors = new HashSet<Proveedor>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
         public string Estado { get; set; } ="A"; 
        public int Idprovincia { get; set; }

        public virtual Provincia IdprovinciaNavigation { get; set; } 
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Empleado> Empleados { get; set; }
        public virtual ICollection<Persona> Personas { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}