// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Cliente
    {
        public int Id { get; set; }
        public int IdPersona { get; set; }
        public string Empresa { get; set; } 
        public int IdCiudad { get; set; }
        public int IdCuenta { get; set; }
        public int IdPago { get; set; }
        public int IdEmpresa { get; set; }

        public virtual Ciudad IdCiudadNavigation { get; set; } 
        public virtual Cuentum IdCuentaNavigation { get; set; } 
        public virtual Empresa IdEmpresaNavigation { get; set; } 
        public virtual Pago IdPagoNavigation { get; set; } 
        public virtual Persona IdPersonaNavigation { get; set; } 
    }
}