// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Cuentum
    {
        public Cuentum()
        {
            Clientes = new HashSet<Cliente>();
            Proveedors = new HashSet<Proveedor>();
        }

        public int Id { get; set; }
        public string NumCuenta { get; set; } 
        public string TipoCuenta { get; set; } 
         public string Estado { get; set; } ="A"; 
        public int Idbanco { get; set; }
        public int IdTipoCuenta { get; set; }

        public virtual Banco IdBancoNavigation { get; set; } 
        public virtual Tipocuentum IdTipoCuentaNavigation { get; set; } 
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}