// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Empleado
    {
        public int Id { get; set; }
        public int Idpersona { get; set; }
        public string Empresa { get; set; } 
        public float Sueldo { get; set; }
        public DateTime? Fechacontrato { get; set; }
        public int Idciudad { get; set; }

        public virtual Ciudad IdciudadNavigation { get; set; } 
        public virtual Persona IdpersonaNavigation { get; set; } 
    }
}