// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Evento
    {
        public Evento()
        {
            PresupuestoNavegation = new HashSet<Presupuesto>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
        public DateTime Fechaevento { get; set; }
        public string Localidad { get; set; } 
        public string Promotor { get; set; } 
        public string Artista { get; set; } 
         public string Estado { get; set; } ="A"; 

        public virtual ICollection<Presupuesto> PresupuestoNavegation { get; set; }
    }
}