// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Inventario
    {
        public int Id { get; set; }
        public DateTime FechaAdquirido { get; set; }
        public string Cambio { get; set; }
        public int? CantidadDisponible { get; set; }
        public string EstadoProducto { get; set; } 
        public string TipoMaterial { get; set; } 
         public string Estado { get; set; } ="A"; 
        public int Idusuario { get; set; }
        public int Idproducto { get; set; }

        public virtual Producto IdproductoNavigation { get; set; } 
        public virtual Usuario IdusuarioNavigation { get; set; } 
    }
}