// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class PresupuestoDetalle
    {
        public int Id { get; set; }
        public string Servicio { get; set; } 
        public int IdServicio { get; set; }
        public int IdProducto { get; set; }
        public int IdCabPresupuesto { get; set; }

        public virtual Presupuesto IdPresupuestoNavigation { get; set; } 
        public virtual Producto IdproductoNavigation { get; set; } 
        public virtual Servicio IdservicioNavigation { get; set; } 
    }
}