// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Presupuesto
    {
        public Presupuesto()
        {
            Detpresupuestos = new HashSet<PresupuestoDetalle>();
        }

        public int Id { get; set; }
        public int Codigo { get; set; }
        public float Version { get; set; }
        public string Descripcion { get; set; } 
        public string Lugar { get; set; } 
        public DateTime FechaEvento { get; set; }
        public DateTime FechaCotizacion { get; set; }
        public float Descuento { get; set; }
        public float Iva { get; set; }
        public float Total { get; set; }
         public string Estado { get; set; } ="A"; 
        public int IdEvento { get; set; }

        public virtual Evento IdeventoNavigation { get; set; } 
        public virtual ICollection<PresupuestoDetalle> Detpresupuestos { get; set; }
    }
}