// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Producto
    {
        public Producto()
        {
            Detpresupuestos = new HashSet<PresupuestoDetalle>();
            Inventarios = new HashSet<Inventario>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
        public int Cantidad { get; set; }
        public float Precio { get; set; }
         public string Estado { get; set; } ="A"; 
        public int Idcategoria { get; set; }

        public virtual Categorium IdcategoriaNavigation { get; set; } 
        public virtual ICollection<PresupuestoDetalle> Detpresupuestos { get; set; }
        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}