// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Provincia
    {
        public Provincia()
        {
            Ciudads = new HashSet<Ciudad>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
         public string Estado { get; set; } ="A"; 

        public virtual ICollection<Ciudad> Ciudads { get; set; }
    }
}