// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Servicio
    {
        public Servicio()
        {
            Detpresupuestos = new HashSet<PresupuestoDetalle>();
            Proveedors = new HashSet<Proveedor>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; } 
         public string Estado { get; set; } ="A"; 

        public virtual ICollection<PresupuestoDetalle> Detpresupuestos { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}