// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace Datos.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Inventarios = new HashSet<Inventario>();
        }

        public int Id { get; set; }
        public int Idpersona { get; set; }
        public string Us { get; set; } 
        public string Clave { get; set; } 
        public int Idrol { get; set; }
         public string Estado { get; set; } ="A";

        public virtual Persona IdpersonaNavigation { get; set; } 
        public virtual Rol IdrolNavigation { get; set; } 
        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}