// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using Datos.AplicationDB.Configurations;
using Datos.Models;
using MySql.EntityFrameworkCore.Extensions;


namespace Datos.AplicationDB
{
    public partial class SistemapContext : DbContext
    {
        
        public SistemapContext(DbContextOptions<SistemapContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<Presupuesto> Cabpresupuestos { get; set; }
        public virtual DbSet<Categorium> Categoria { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Cuentum> Cuenta { get; set; }
        public virtual DbSet<PresupuestoDetalle> Detpresupuestos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Tipocuentum> Tipocuenta { get; set; }
        public virtual DbSet<Tipoempresa> Tipoempresas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
         
        modelBuilder.ApplyConfiguration(new Configurations.BancoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CabpresupuestoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CategoriumConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CiudadConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CuentumConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DetpresupuestoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmpleadoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmpresaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EventoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.InventarioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PagoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProductoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProveedorConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProvinciumConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ServicioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipocuentumConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TipoempresaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
