// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class CabpresupuestoConfiguration : IEntityTypeConfiguration<Presupuesto>
    {
        public void Configure(EntityTypeBuilder<Presupuesto> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("cabpresupuesto");

            entity.HasIndex(e => e.IdEvento).HasName("evento_cabprefk");

            entity.Property(e => e.Id).HasColumnName("idcabpresupuesto");

            entity.Property(e => e.Codigo).HasColumnName("codigo");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("descripcion");

            entity.Property(e => e.Descuento).HasColumnName("descuento");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("estado")
                .IsFixedLength();

            entity.Property(e => e.FechaCotizacion).HasColumnName("fechaCotizacion");

            entity.Property(e => e.FechaEvento).HasColumnName("fechaEvento");

            entity.Property(e => e.IdEvento).HasColumnName("idevento");

            entity.Property(e => e.Iva).HasColumnName("iva");

            entity.Property(e => e.Lugar)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("lugar");

            entity.Property(e => e.Total).HasColumnName("total");

            entity.Property(e => e.Version).HasColumnName("version");

            entity.HasOne(d => d.IdeventoNavigation)
                .WithMany(p => p.PresupuestoNavegation)
                .HasForeignKey(d => d.IdEvento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("evento_cabprefk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Presupuesto> entity);
    }
}
