// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class CiudadConfiguration : IEntityTypeConfiguration<Ciudad>
    {
        public void Configure(EntityTypeBuilder<Ciudad> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("ciudad");

            entity.HasIndex(e => e.Idprovincia).HasName("provincia_ciudadfk");

            entity.Property(e => e.Id).HasColumnName("idciudad");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("descripcion");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("estado")
                .IsFixedLength();

            entity.Property(e => e.Idprovincia).HasColumnName("idprovincia");

            entity.HasOne(d => d.IdprovinciaNavigation)
                .WithMany(p => p.Ciudads)
                .HasForeignKey(d => d.Idprovincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("provincia_ciudadfk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ciudad> entity);
    }
}
