// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class ClienteConfiguration : IEntityTypeConfiguration<Cliente>
    {
        public void Configure(EntityTypeBuilder<Cliente> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("cliente");

            entity.HasIndex(e => e.IdCiudad).HasName("ciudad_clientefk");

            entity.HasIndex(e => e.IdPersona).HasName("cliente_personafk");

            entity.HasIndex(e => e.IdCuenta).HasName("cuenta_clientefk");

            entity.HasIndex(e => e.IdEmpresa).HasName("empresa_clientefk");

            entity.HasIndex(e => e.IdPago).HasName("pago_clientefk");

            entity.Property(e => e.Id).HasColumnName("idcliente");

            entity.Property(e => e.Empresa)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("empresa");

            entity.Property(e => e.IdCiudad).HasColumnName("idciudad");

            entity.Property(e => e.IdCuenta).HasColumnName("idcuenta");

            entity.Property(e => e.IdEmpresa).HasColumnName("idempresa");

            entity.Property(e => e.IdPago).HasColumnName("idpago");

            entity.Property(e => e.IdPersona).HasColumnName("idpersona");

            entity.HasOne(d => d.IdCiudadNavigation)
                .WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdCiudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ciudad_clientefk");

            entity.HasOne(d => d.IdCuentaNavigation)
                .WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdCuenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cuenta_clientefk");

            entity.HasOne(d => d.IdEmpresaNavigation)
                .WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdEmpresa)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("empresa_clientefk");

            entity.HasOne(d => d.IdPagoNavigation)
                .WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pago_clientefk");

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cliente_personafk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cliente> entity);
    }
}
