// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class CuentumConfiguration : IEntityTypeConfiguration<Cuentum>
    {
        public void Configure(EntityTypeBuilder<Cuentum> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("cuenta");

            entity.HasIndex(e => e.Idbanco).HasName("banco_cuentafk");

            entity.HasIndex(e => e.IdTipoCuenta).HasName("tipocuenta_cuentafk");

            entity.Property(e => e.Id).HasColumnName("idcuenta");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("estado")
                .IsFixedLength();

            entity.Property(e => e.Idbanco).HasColumnName("idbanco");

            entity.Property(e => e.IdTipoCuenta).HasColumnName("idtipocuenta");

            entity.Property(e => e.NumCuenta)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("numCuenta");

            entity.Property(e => e.TipoCuenta)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("tipoCuenta");

            entity.HasOne(d => d.IdBancoNavigation)
                .WithMany(p => p.Cuenta)
                .HasForeignKey(d => d.Idbanco)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("banco_cuentafk");

            entity.HasOne(d => d.IdTipoCuentaNavigation)
                .WithMany(p => p.Cuenta)
                .HasForeignKey(d => d.IdTipoCuenta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("tipocuenta_cuentafk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cuentum> entity);
    }
}
