// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class DetpresupuestoConfiguration : IEntityTypeConfiguration<PresupuestoDetalle>
    {
        public void Configure(EntityTypeBuilder<PresupuestoDetalle> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("detpresupuesto");

            entity.HasIndex(e => e.IdCabPresupuesto).HasName("cabpresupuesto_detprefk");

            entity.HasIndex(e => e.IdProducto).HasName("producto_detprefk");

            entity.HasIndex(e => e.IdServicio).HasName("servicio_detprefk");

            entity.Property(e => e.Id).HasColumnName("iddetPresupuesto");

            entity.Property(e => e.IdCabPresupuesto).HasColumnName("idcabpresupuesto");

            entity.Property(e => e.IdProducto).HasColumnName("idproducto");

            entity.Property(e => e.IdServicio).HasColumnName("idservicio");

            entity.Property(e => e.Servicio)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("servicio");

            entity.HasOne(d => d.IdPresupuestoNavigation)
                .WithMany(p => p.Detpresupuestos)
                .HasForeignKey(d => d.IdCabPresupuesto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cabpresupuesto_detprefk");

            entity.HasOne(d => d.IdproductoNavigation)
                .WithMany(p => p.Detpresupuestos)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("producto_detprefk");

            entity.HasOne(d => d.IdservicioNavigation)
                .WithMany(p => p.Detpresupuestos)
                .HasForeignKey(d => d.IdServicio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("servicio_detprefk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PresupuestoDetalle> entity);
    }
}
