// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class EmpleadoConfiguration : IEntityTypeConfiguration<Empleado>
    {
        public void Configure(EntityTypeBuilder<Empleado> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("empleado");

            entity.HasIndex(e => e.Idciudad).HasName("ciudad_empleadofk");

            entity.HasIndex(e => e.Idpersona).HasName("empleado_personafk");

            entity.Property(e => e.Id).HasColumnName("idempleado");

            entity.Property(e => e.Empresa)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("empresa");

            entity.Property(e => e.Fechacontrato).HasColumnName("fechacontrato");

            entity.Property(e => e.Idciudad).HasColumnName("idciudad");

            entity.Property(e => e.Idpersona).HasColumnName("idpersona");

            entity.Property(e => e.Sueldo).HasColumnName("sueldo");

            entity.HasOne(d => d.IdciudadNavigation)
                .WithMany(p => p.Empleados)
                .HasForeignKey(d => d.Idciudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ciudad_empleadofk");

            entity.HasOne(d => d.IdpersonaNavigation)
                .WithMany(p => p.Empleados)
                .HasForeignKey(d => d.Idpersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("empleado_personafk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empleado> entity);
    }
}
