// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class PersonaConfiguration : IEntityTypeConfiguration<Persona>
    {
        public void Configure(EntityTypeBuilder<Persona> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("persona");

            entity.HasIndex(e => e.Cedula).HasName("cedula")
                .IsUnique();

            entity.HasIndex(e => e.Idciudad).HasName("ciudad_personafk");

            entity.Property(e => e.Id).HasColumnName("idpersona");

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("apellido");

            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("cedula");

            entity.Property(e => e.Celular)
                .HasMaxLength(15)
                .HasColumnName("celular");

            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("correo");

            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("direccion");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("estado")
                .IsFixedLength();

            entity.Property(e => e.Genero)
                .HasMaxLength(30)
                .HasColumnName("genero");

            entity.Property(e => e.Idciudad).HasColumnName("idciudad");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");

            entity.Property(e => e.Telefono)
                .HasMaxLength(15)
                .HasColumnName("telefono");

            entity.HasOne(d => d.IdciudadNavigation)
                .WithMany(p => p.Personas)
                .HasForeignKey(d => d.Idciudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ciudad_personafk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Persona> entity);
    }
}
