// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using Datos.AplicationDB;
using Datos.Models;

namespace Datos.AplicationDB.Configurations
{
    public partial class ProductoConfiguration : IEntityTypeConfiguration<Producto>
    {
        public void Configure(EntityTypeBuilder<Producto> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("PRIMARY");

            entity.ToTable("producto");

            entity.HasIndex(e => e.Idcategoria).HasName("categoria_productofk");

            entity.Property(e => e.Id).HasColumnName("idproducto");

            entity.Property(e => e.Cantidad).HasColumnName("cantidad");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("descripcion");

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("estado")
                .IsFixedLength();

            entity.Property(e => e.Idcategoria).HasColumnName("idcategoria");

            entity.Property(e => e.Precio).HasColumnName("precio");

            entity.HasOne(d => d.IdcategoriaNavigation)
                .WithMany(p => p.Productos)
                .HasForeignKey(d => d.Idcategoria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("categoria_productofk");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Producto> entity);
    }
}
